application: plinehandotcom-hrd
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /admin
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: plinehandotcom.py
